[project]
name = "venuepass-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DevAhmadYarKhan", email = "210438969+DevAhmadYarKhan@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.118.0",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "httpx2>=2.13.1",
    "pytest>=8.4.2",
]

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
