"""create events table

Revision ID: 20260925_0001
Revises:
Create Date: 2026-09-25

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Alembic uses these identifiers to order the migration graph. This is the root
# revision, so it has no predecessor.
revision: str = "20260925_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the initial events table."""
    op.create_table(
        "events",

        # PostgreSQL generates UUIDs so inserts outside the ORM remain valid.
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        # Core event details and timezone-aware schedule.
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("venue", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        # Capacity and lifecycle state drive future reservation behavior.
        sa.Column("capacity", sa.Integer(), nullable=False),
        # Audit timestamps are generated by PostgreSQL rather than API clocks.
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "cancelled",
                "completed",
                name="event_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Database constraints preserve invariants for every writer.
        sa.CheckConstraint(
            "capacity > 0",
            name="ck_events_capacity_positive",
        ),
        sa.CheckConstraint(
            "ends_at > starts_at",
            name="ck_events_valid_time_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Drop the events table."""
    # Dropping the table also removes its indexes and CHECK constraints.
    op.drop_table("events")
